# Generated by Django 5.1 on 2024-12-18 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
