# Generated by Django 5.1 on 2024-12-18 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_category_rename_created_at_name_input_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('input_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=255)),
                ('input_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
